### ISSUE TITLE
Build error - 

### ISSUE THREAD

**Issue by daviddelmonte** [comyar/Chronos-Swift#11]
Hi, I must be doing something wrong.. I get the following error on lines 141 and 155:

Initializer for conditional binding must have Optional type, not 'dispatch_source_t' (aka 'OS_dispatch_source')

Any help appreciated..

**Comment by minhphamuit91** [comment]
I also have this issue, please help...

**Comment by comyar** [comment]
Hey sorry for the late response, I've started looking into this...

**Comment by comyar** [comment]
Do either of you have a code sample to reproduce the issue? I haven't been able to reproduce this on my end. Are you using Cocoa Pods?

**Comment by daviddelmonte** [comment]
Hi, thanks for looking at this.

Here’s a sample, and I’m sorry but I don’t use CocoaPods.

David

**Comment by comyar** [comment]
@daviddelmonte Sorry, but I don't see a sample on my end...could you post it again?

**Comment by comyar** [comment]
Ah, I've discovered the issue...Swift 3.0 😉. Currently working on an update...

**Comment by daviddelmonte** [comment]
Great!! Thanks. Do you still want me to send a sample?I sent it via email before.. Next time, I'll add it to my message..

**Comment by comyar** [comment]
No, shouldn't be necessary. I'll try to get an update out this weekend.

**Comment by comyar** [comment]
I've pushed out a fix for this, so I'll close out this issue. If you run into any problems, feel free to reopen this issue.
