### ISSUE TITLE
Build test error: Integer overflows

### ISSUE THREAD

**Issue by lesslucifer** [comyar/Chronos-Swift#14]
I got this error when build project with carthage.

ChronosTests/DispatchTimerTests.swift:38:96: error: integer overflows when converted from 'UInt64' to 'Int'
      return DispatchTime(uptimeNanoseconds: DispatchTime.now().uptimeNanoseconds.advanced(by: Int(5 * NSEC_PER_SEC)))

**Comment by comyar** [comment]
What version of Xcode are you using? I'm not able to recreate this on 8.1.

**Comment by comyar** [comment]
I believe this is fixed by #16, so closing. Feel free to reopen this issue if you run into the problem again.
