### ISSUE TITLE
Crash on iphone 5

### ISSUE THREAD

**Issue by ggiampietro** [comyar/Chronos-Swift#15]
Hi! I been using this library for a while and I like, thanks.
The start function crash in  when call scheduleRepeating due an overflow

```swift
open func start(_ now: Bool) {
        validate()
        if OSAtomicCompareAndSwap32Barrier(State.paused, State.running, &running) {
          timer.scheduleRepeating(deadline: startTime(interval, now: now), interval: DispatchTimeInterval.nanoseconds(Int(interval.multiplied(by: Double(NSEC_PER_SEC)))))
            timer.resume()
        }
    }
```

Also when you run the unit test in the iphone 5 you get this error message: "DispatchTimerTests.swift:38:96: Integer overflows when converted from 'UInt64' to 'Int'"

I will make a pr for this issue.
Thanks

**Comment by comyar** [comment]
Thanks again for the contribution! I'll try to get a Cocoa Pods release out sometime this week, however if you can't wait for that, your changes are now in `master` so you'll be able to point Cocoa Pods to head of `master` for the time being.

**Comment by ggiampietro** [comment]
Great! Thanks to you!
